name: Deploy Hugo

on:
  push:
    branches:
      - master  

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.94.2'
          extended: true

      - name: Build Hugo Site
        run: hugo --minify --gc
        
      - name: Push to yanbo92.site
        uses: cpina/github-action-push-to-another-repository@v1.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.personal_token }}
        with:
          source-directory: './public'
          destination-github-username: 'yanbo92'
          destination-repository-name: 'yanbo92.site'
          user-email: yanbo92@139.com
          
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.personal_token }} 
          PUBLISH_BRANCH: gh-pages  
          PUBLISH_DIR: ./public 
          commit_message: ${{ github.event.head_commit.message }}
          
          
