name: Deploy Hugo

on:
  push:
    branches:
      - master  

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.94.2'
          extended: true

      - name: Build Hugo Site
        run: hugo --minify --gc
        

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.personal_token }} 
          PUBLISH_BRANCH: gh-pages  
          PUBLISH_DIR: ./public 
          commit_message: ${{ github.event.head_commit.message }}
          
          
